export const COUNTRIES = [
  { code: "TR", name: "تركيا" },
  { code: "SA", name: "السعودية" },
  { code: "AE", name: "الإمارات" },
  { code: "QA", name: "قطر" },
  { code: "KW", name: "الكويت" },
  { code: "BH", name: "البحرين" },
  { code: "OM", name: "عُمان" },
  { code: "JO", name: "الأردن" },
  { code: "LB", name: "لبنان" },
  { code: "IQ", name: "العراق" },
  { code: "EG", name: "مصر" },
  { code: "LY", name: "ليبيا" },
  { code: "TN", name: "تونس" },
  { code: "DZ", name: "الجزائر" },
  { code: "MA", name: "المغرب" },
  { code: "SD", name: "السودان" },
  { code: "YE", name: "اليمن" },
  { code: "DE", name: "ألمانيا" },
  { code: "FR", name: "فرنسا" },
  { code: "NL", name: "هولندا" },
  { code: "BE", name: "بلجيكا" },
  { code: "CH", name: "سويسرا" },
  { code: "AT", name: "النمسا" },
  { code: "SE", name: "السويد" },
  { code: "NO", name: "النرويج" },
  { code: "DK", name: "الدنمارك" },
  { code: "FI", name: "فنلندا" },
  { code: "GB", name: "المملكة المتحدة" },
  { code: "IE", name: "أيرلندا" },
  { code: "US", name: "الولايات المتحدة" },
  { code: "CA", name: "كندا" },
  { code: "BR", name: "البرازيل" },
  { code: "AR", name: "الأرجنتين" },
  { code: "MX", name: "المكسيك" },
  { code: "IN", name: "الهند" },
  { code: "PK", name: "باكستان" },
  { code: "BD", name: "بنغلادش" },
  { code: "ID", name: "إندونيسيا" },
  { code: "MY", name: "ماليزيا" },
  { code: "SG", name: "سنغافورة" },
  { code: "TH", name: "تايلاند" },
  { code: "CN", name: "الصين" },
  { code: "JP", name: "اليابان" },
  { code: "KR", name: "كوريا الجنوبية" },
  { code: "RU", name: "روسيا" },
  { code: "UA", name: "أوكرانيا" },
  { code: "AU", name: "أستراليا" },
  { code: "NZ", name: "نيوزيلندا" },
  { code: "ZA", name: "جنوب أفريقيا" }
];

export const getCountryPage = (page = 0, pageSize = 8) => {
  const start = page * pageSize;
  return COUNTRIES.slice(start, start + pageSize);
};
